title:              Flora Zhang
email:              zhangfl@oregonstate.edu
description:        My website!
author:             Flora Zhang
# baseurl:           
url:                "https://florazhang.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    TealTheAvocado
# facebook_username:  StartBootstrap
instagram_username:  florazhanng
linkedin_username: florazhang24

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
